baseURL = "/"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
languageCode = "es"
title = "para plantilla simple hugo"
theme = "tema-simple-hugo"

pluralizeListTitles = false
# canonifyurls = true

DefaultContentLanguage = "es"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

# para que se genere las páginas con fecha posterior a hoy
buildFuture = true

[params]
    navigation = ["motivacion","casas","calendario.md"]

[outputs]
home = [ "HTML", "RSS", "JSON"]
section = ["HTML", "JSON"]

# crea el contenido del directorio bitacora con una estructura como la que 
# usaba en jekyll 
[permalinks]
## bitacora = "/:year/:month/:day/bitacora/"
post = "/:year/:month/:day/"
motivacion = "/motivacion/:filename"