baseURL = "/"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
languageCode = "es"
title = "para plantilla simple hugo"
theme = "tema-simple-hugo"

pluralizeListTitles = false
# canonifyurls = true

# para poder usar emojis
enableEmoji = true

DefaultContentLanguage = "es"
metaDataFormat = "yaml"

# para resaltar el código
# pygmentsUseClasses = true
# pygmentCodeFences = true
pygmentsUseClasses = false
# choose one:
#pygmentsStyle = "autumn"
#pygmentsStyle = "borland"
#pygmentsStyle = "bw"
#pygmentsStyle = "colorful"
#pygmentsStyle = "default"
# pygmentsStyle = "emacs"
#pygmentsStyle = "friendly"
#pygmentsStyle = "fruity"
#pygmentsStyle = "manni"
pygmentsStyle = "monokai"
#pygmentsStyle = "murphy"
#pygmentsStyle = "native"
#pygmentsStyle = "pastie"
#pygmentsStyle = "perldoc"
#pygmentsStyle = "rrt"
#pygmentsStyle = "tango"
#pygmentsStyle = "trac"
#pygmentsStyle = "vim"
#pygmentsStyle = "vs"

#disqusShortname = "XXX"
#googleAnalytics = "XXX"

# para que se genere las páginas con fecha posterior a hoy
buildFuture = true

[params]
    navigation = ["motivacion","casas","calendario.md"]

[outputs]
home = [ "HTML", "RSS", "JSON"]
section = ["HTML", "JSON"]

# crea el contenido del directorio bitacora con una estructura como la que 
# usaba en jekyll 
[permalinks]
## bitacora = "/:year/:month/:day/bitacora/"
post = "/:year/:month/:day/"
motivacion = "/motivacion/:filename"